# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1174, 613)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(720, 100, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(430, 120, 20, 461))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(440, 150, 21, 401))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(2)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(420, 150, 21, 401))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.line_4.setFont(font)
        self.line_4.setLineWidth(2)
        self.line_4.setMidLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_HandLeft = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_HandLeft.setGeometry(QtCore.QRect(30, 310, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        self.pushButton_HandLeft.setFont(font)
        self.pushButton_HandLeft.setObjectName("pushButton_HandLeft")
        self.pushButton_HandRight = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_HandRight.setGeometry(QtCore.QRect(310, 310, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        self.pushButton_HandRight.setFont(font)
        self.pushButton_HandRight.setObjectName("pushButton_HandRight")
        self.pushButton_HandUp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_HandUp.setGeometry(QtCore.QRect(170, 190, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        self.pushButton_HandUp.setFont(font)
        self.pushButton_HandUp.setObjectName("pushButton_HandUp")
        self.pushButton_HandDown = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_HandDown.setGeometry(QtCore.QRect(170, 430, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        self.pushButton_HandDown.setFont(font)
        self.pushButton_HandDown.setObjectName("pushButton_HandDown")
        self.pushButton_BodyLeft = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BodyLeft.setGeometry(QtCore.QRect(480, 310, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setKerning(True)
        self.pushButton_BodyLeft.setFont(font)
        self.pushButton_BodyLeft.setObjectName("pushButton_BodyLeft")
        self.pushButton_BodyRight = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BodyRight.setGeometry(QtCore.QRect(760, 310, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setKerning(True)
        self.pushButton_BodyRight.setFont(font)
        self.pushButton_BodyRight.setObjectName("pushButton_BodyRight")
        self.pushButton_BodyDown = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BodyDown.setGeometry(QtCore.QRect(620, 430, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setKerning(True)
        self.pushButton_BodyDown.setFont(font)
        self.pushButton_BodyDown.setObjectName("pushButton_BodyDown")
        self.pushButton_BodyUp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BodyUp.setGeometry(QtCore.QRect(620, 190, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setKerning(True)
        self.pushButton_BodyUp.setFont(font)
        self.pushButton_BodyUp.setObjectName("pushButton_BodyUp")
        self.comboBox_State = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_State.setGeometry(QtCore.QRect(920, 190, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_State.setFont(font)
        self.comboBox_State.setAcceptDrops(False)
        self.comboBox_State.setAutoFillBackground(False)
        self.comboBox_State.setEditable(False)
        self.comboBox_State.setIconSize(QtCore.QSize(20, 25))
        self.comboBox_State.setObjectName("comboBox_State")
        self.comboBox_State.addItem("")
        self.comboBox_State.addItem("")
        self.comboBox_State.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(920, 100, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(890, 100, 20, 461))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(2)
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_StateSwitch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StateSwitch.setGeometry(QtCore.QRect(920, 270, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        self.pushButton_StateSwitch.setFont(font)
        self.pushButton_StateSwitch.setObjectName("pushButton_StateSwitch")
        self.lineEdit_API = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_API.setGeometry(QtCore.QRect(120, 40, 781, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_API.setFont(font)
        self.lineEdit_API.setObjectName("lineEdit_API")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(20, 80, 1041, 20))
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_APIcall = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_APIcall.setGeometry(QtCore.QRect(920, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.pushButton_APIcall.setFont(font)
        self.pushButton_APIcall.setObjectName("pushButton_APIcall")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hand"))
        self.label_2.setText(_translate("MainWindow", "Body"))
        self.pushButton_HandLeft.setText(_translate("MainWindow", "Left"))
        self.pushButton_HandRight.setText(_translate("MainWindow", "Right"))
        self.pushButton_HandUp.setText(_translate("MainWindow", "Up"))
        self.pushButton_HandDown.setText(_translate("MainWindow", "Down"))
        self.pushButton_BodyLeft.setText(_translate("MainWindow", "←"))
        self.pushButton_BodyRight.setText(_translate("MainWindow", "→"))
        self.pushButton_BodyDown.setText(_translate("MainWindow", "↓"))
        self.pushButton_BodyUp.setText(_translate("MainWindow", "↑"))
        self.comboBox_State.setCurrentText(_translate("MainWindow", "Autonomous"))
        self.comboBox_State.setItemText(0, _translate("MainWindow", "Autonomous"))
        self.comboBox_State.setItemText(1, _translate("MainWindow", "Semi_Autonomous"))
        self.comboBox_State.setItemText(2, _translate("MainWindow", "Manual"))
        self.label_3.setText(_translate("MainWindow", "State"))
        self.pushButton_StateSwitch.setText(_translate("MainWindow", "Switch"))
        self.label_4.setText(_translate("MainWindow", "API :"))
        self.pushButton_APIcall.setText(_translate("MainWindow", "Call"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
